purduesigbots/pros-vsc

package.json
src/extension.ts

This PR adds appropriate commands to the `activationEvents` array in `package.json` and hides commands which can only be run inside a PROS project from the command palette when a `project.pros` can't be located in the workspace root.
Adding commands like `pros.new` as an activation event allows users to call them without getting a command not defined error. This means that new projects can be created without opening an existing one.
Hiding commands which can't do anything without a proper project open prevents users from misusing the extension unintentionally.
The code for detecting `project.pros` does not recursively look for the file like the activation event does and it does not iterate through every workspace. However, in 95% of cases it should work just fine. It is also located in …

Command user experience updates

---

package.json

Should clear up confusion and just make the extension easier to use.

Activate Extension when clicking on the sidebar.

---

package-lock.json
src/extension.ts

Add an entry to compile_commands.json for new files created in a project
Sometimes intellisense/code completion/etc can have issues when a new file is created because there's not yet an entry for it in the compilation database.
This change makes it so that users don't need to wait until their new files are minimally compilable before their code completion works.
N/A

🚸 Generate a CDB entry for files when they are created in a project

---

src/commands/upload.ts

Gives the upload command a 50MB buffer to fix the "unexpected end of JSON input" error. This is just temporary until we get the middleware working.

🐛Hotfix for upload max buffer exceeded

---

package.json
src/extension.ts
src/one-click/download.ts
src/one-click/install.ts
src/views/tree-view.ts

**Summary:**
Adds a new sidebar button and command to check if there is a CLI update and update only the CLI, not the toolchain.
**Motivation:**
Currently, the only way to update the CLI is by uninstalling and reinstalling PROS, which includes the ~200MB toolchain. These changes allow the user to update only the CLI, resulting in a much faster update.
**Test Case:**
Installed an outdated CLI version (3.2.2) into the one-click path and tested new command. The outdated CLI was deleted and the newest version was downloaded. The toolchain remained the same. This process was significantly faster than waiting for both the CLI and toolchain to download.

✨Button to Update Only CLI

---

src/views/welcome-view.ts

Super simple minor cosmetic thing. It just bothers me every time I see it. ;)

missing space after link on welcome page

---

src/commands/create-project.ts
src/extension.ts
src/one-click/download.ts
src/one-click/install.ts
src/one-click/installed.ts

Fixed a few minor issues while poking around in my PROS install today:
- `compile-commands.json` is now generated when a PROS project is opened
- Race conditions with the environment variables are now fixed by lazily setting the variables when a PROS terminal is needed
- Clicking "Update PROS" when the CLI is not installed now shows the correct message.
~~These changes, however, do **NOT** fully solve the issue in #47. Running `pros build-compile-commands` has no effect when run against a project that has been successfully built and produces the message `make: Nothing to be done for 'quick'.` Creating a new project or opening an existing project without `compile-commands.json` will not currently produce a new `compile-commands.json` file. I can think of a few solutions to this:~~
- ~~Set …

Generate compile-commands on launch + race cond fixes + update text fix

---

package.json

Many users have issues with IntelliSense showing errors that are not real. Installing the clangd extension will resolve these issues without the user having to configure anything.
vtow
vtow

🚸Add clangd to extension dependencies

---

package.json
src/commands/build.ts
src/commands/buildUpload.ts
src/commands/capture.ts
src/commands/clean.ts
src/commands/create-project.ts
src/commands/upgrade-project.ts
src/commands/upload.ts
src/one-click/download.ts
src/one-click/install.ts
src/one-click/installed.ts

This PR does two things:
1) It replaces the current windows toolchain URL (azure artifact that no longer exists) with a link to the most recent release on https://github.com/purduesigbots/toolchain, looking for the file `pros-toolchain-windows.zip`. Whenever we update the toolchain we need to make a new release on that repo and one-click will use that toolchain.
2) It allows users to put their own URLs for downloading the cli and toolchain. This allows more advanced users to refer to specific toolchain/cli versions, or do what #67 wants to do. 
This shouldn't be merged until we get a working toolchain onto the toolchain repo and test one-click on windows.

✨🐛Fix Toolchain downloand and support custom urls.

---

src/one-click/install.ts

The modified PATH started with the path separator and was then missing that path separator in between the toolchain and the original path. There was also a bug where it would modify the path twice. Not sure the extent of weird behavior this caused, but it will probably help at least a few users.

🐛Fix PATH Separator Issue

---

package-lock.json
package.json
src/extension.ts

Summary:
This code allows user to choose which pros project to work on. When clicking the pros tap on VSC it will bring up a selection of folders the users can choose to work on. 
References:
Allow multiple pros projects in workspace (Issue #26)
Test Plan:
First open up a folder/directory that **does** contain a pros project folder in VSC. Then you can click the pros tab and check if the relevant folders show up for selection when the file selection pops up. Another test needed is to open up a folder/directory that **doesn't** contain a pros project folder. Then the file selection should show up but nothing should be available to select.

 ✨ Select PROS Project from directory

---

package.json
src/commands/fw-update.ts
src/commands/index.ts
src/extension.ts
src/views/tree-view.ts
src/views/welcome-view.ts

Adds a command that runs `vexcom --vexos latest`. 
I've tested that the error message of "No device found" shows up correctly when running the command on my machine, but I don't have access to a V5 brain to test that this works fully.

✨Add support for VexOS firmware updating

---

src/commands/base-command.ts
src/extension.ts
src/workspace.ts

Does what the title says. Adds a method to attempt to get 1) the current workspace folder Uri and 2) if it is a PROS project or not. Firstly tries to get the active text editor, and if that does not work it uses the 0th index of workspace folders. throws an error if there are no workspace folders, so be sure to catch it.

get current workspace folder and PROS project slightly better.

---

src/commands/base-command.ts
src/commands/buildUpload.ts
src/extension.ts
src/logger.ts

This pull request does a lot.
1. Handle Click confirm and prompt dialogs. Confirm dialogs will create a warning message with options for "Yes" and "No", prompt dialogs will create a warning message with the options specified. I haven't fully figured out the regex for prompts, but that's ok since prompts are only used when multiple ports are detected.
2. Create explicit type for command_data_json. This ensures that when constructing a Base_Command, you have to provide all of the necessary data.
3. Add outputs from the child process to PROS Output. If an error has occurred, show a button to view the output. This mirrors the behavior of parseMakeOutput.
4. Add example usage of Base_Command in buildUpload.ts. This was mainly for testing purposes, but I thought why not include it in the pull …

Improve Output Parsing

---

src/commands/capture.ts
src/commands/clean.ts
src/commands/command_tools.ts
src/commands/run.ts
src/commands/stop.ts
src/commands/upgrade-project.ts

Code for the following sidebar commands was rewritten to be more concise using the Base Command:
capture,
clean,
run,
stop,
upgrade project.

Rewrote some sidebar commands to incorporate Base Command 

---

src/views/welcome-view.ts

Code was commented, which causes the recent CLI and Kernel versions to show as 0.0.0 in the welcome view. This fixes that.

Uncomment Functions in Welcome View

---

src/one-click/install.ts

If everything is working, close the installing PROS progress message without waiting for the user to close the information message.

🐛Don't wait for user to close confirmation message

---

src/commands/base-command.ts
src/commands/build.ts
src/commands/command_tools.ts
src/one-click/install.ts
src/workspace.ts

- Add checking for build errors in BaseCommand
- Change selectKernelVersion to use `pros` instead of `prosv5`
- Fix issue on Mac where CLI is shown as not up to date (#113)
- Make getCwdIsPros to be less reliant on activeTextEditor

🐛 Bugfixes for MacOS (and other stuff)

---

src/commands/command_tools.ts

Change prompt to Select Folder instead of Select File and prevent single file selection for directory selection.

🐛 Change Select Directory to Select Folder

---

src/commands/upgrade-project.ts

Stops upgrade process if user selects no to upgrade or clicks out of picker.

🐛 Stop Upgrade Project if the user chooses

---

src/commands/base-command.ts

Now shows an ERROR message on Run, Stop, and Capture commands when no brain is plugged in. This does however now throw two errors for Upload and other commands that print two errors to the terminal. Needs to be some sort of better solution for this.

🐛 Check for Error message without colon

---

package.json
src/extension.ts
src/logger.ts

Creates an extension setting (default 60) for the number of days after which extension logs will be automatically deleted, and deletes old logs upon extension activation.
Closes #138

✨Automatically Delete Old PROS Logs

---

src/one-click/install.ts
src/one-click/installed.ts

currently, if the user had a different toolchain that had arm-none-eabi-g++ but not through the PROS Toolchain, they may encounter problems where the build process is not quite right but verification passed the toolchain installation anyways. This requires the executable to exist under the PROS_TOOLCHAIN directory. Tested on windows, needs mac and/or linux testing.

🐛 Better Toolchain Verification

---

src/extension.ts
src/views/brain-view.ts

Fixes type on getting the experimental feature workspace setting.
Adds a different HTML for brainview if the user does not have experimental features enabled.
Forces Vision Utility to use related features.

🐛 Fix Experimental Features

---

src/device.ts
src/one-click/install.ts

The device search for checking when a v5 device connects/disconnects calls `pros lsusb` every 500 milliseconds, which poses a problem when trying to update the CLI. This PR fixes this issue by suspending the device search while updating the CLI and unsuspending it afterwards.

🐛 Suspend Device Search When Updating CLI

---

src/one-click/install.ts

For Intel Macs, we need quotes around the toolchain path for it to work properly. However, the previous code mistakenly added quotes around the path multiple times. This PR fixes that.

🐛 Fix toolchain verification on Intel Mac

---

.github/workflows/pull_request.yml

Prettier GitHub is causing weird errors, probably due to being on v3 while we're still on v2.

Change Prettier Version on GitHub Action

---

src/extension.ts

Changes the C++ standard in `c_cpp_properties.json` to "gnu++17". This adds some features that are not in standard C++17, such as math constants. We may also want to change the C standard to "gnu17".

🐛 Change IntelliSense C and C++ Standards

---

src/workspace_utils.ts

Automatic project selection would disappear if the user clicked somewhere by mistake, which has led to a lot of problems where users are working in a folder that contains a PROS project, as opposed to working in the PROS project. This should help fix that problem.

:sparkles: Make Project Selection Not Disappear 

---

src/extension.ts

Currently, we require 2 things to use the integrated docs feature:
1) The user is currently in a project
2) The user is on a PROS 4 project
I personally don't think requirement 2 should be a thing, much less requirement 1. If users wish to view the documentation while not in a PROS project they should have the ability. Additionally, the APIs between PROS 3 and PROS 4 are almost entirely the same, so the PROS 4 docs should be mostly fine for PROS 3 users. Since this feature is still in experimental mode, something the user has to enable, I will also assume that the people who will have access to and use this may already be on PROS 4.

🐛Remove Kernel Version Requirement for Integrated Docs

---

package.json

Currently it is activated for all files that end with .pros. This PR changes that to only files called project.pros

:bug: Change when project.pros editor is enabled

---

src/commands/base-command.ts
src/commands/capture.ts
src/commands/command_tools.ts
src/commands/create-project.ts
src/commands/run.ts
src/commands/stop.ts
src/commands/upgrade-project.ts
src/extension.ts

Users with the PROS: Enable Experimental Features setting enabled will have the `Create Project` sidebar button use the `--beta` flag when querying templates and creating the project. Needs a decent amount of integration testing, I only did some quick testing on windows to see if it was functional.

✨ Add beta flag support to create projects

---

package.json
src/extension.ts

somehow brain view got disabled by me (😭 ). This brings it back and makes it only appear if the Experimental Features setting is on, as opposed to just being an empty HTML block that told users to enable the setting.

✨ Brain view change

---

src/commands/base-command.ts
src/commands/build.ts
src/commands/buildUpload.ts
src/commands/clean.ts
src/commands/command_tools.ts
src/commands/upload-command.ts
src/device.ts
src/one-click/install.ts
src/views/tree-view.ts

Bugfixes before we release stuff
- change BaseCommand to add PROS_VSCODE_FLAGS only if the command being run is "pros" and the flags exist
- Remove PROS_VSCODE_FLAGS from args for clean
- Do `pros c ls-templates` instead of `pros c q` for getLatestKernelOkapiVersion
- Stop progress window for install when hitting GitHub rate limit
- Fix TreeButtonMultiSelect to run commands properly

:bug: Pre-Release Fixes

---

src/commands/base-command.ts

Previously we just killed the process, which causes problems with the new prompt to switch to pros 4 when creating a new project. Now we write "N" to stdin, to properly decline the y/N prompt.

:bug: Write "N" to stdin when declining y/N prompts from CLI

---

src/commands/upgrade-project.ts

Our upgrade project message is pretty dumb and always assumes the user has both kernel and okapi installed. This PR does a quick and dirty check for if Okapi is currently installed in their project, and doesn't prompt the user to upgrade Okapi if it isn't installed.

:children_crossing: Don't prompt user to upgrade Okapi if Okapi isn't installed

---

media/brainView.js
src/views/brain-view.ts

Previously, Brain View would update the device info every 3 seconds, which would sometimes interfere with the user running pros CLI commands. This PR uses the usb library to only update the device info when detecting a usb device has connected or disconnected.

🐛 Switch Brain View device info updating to event-based

---

src/commands/base-command.ts
src/commands/buildUpload.ts

In buildUpload, we catch the error in build, but continue to upload even if we fail. So this just adds a return in the catch block so we don't upload if the build fails.

:bug: Don't upload if build fails

---

src/workspace_utils.ts

The VSCode C/C++ extension no longer likes the compile_commands we generate for clangd, probably because we aren't actually compiling for clang. We can either generate a separate compile_commands for the VSCode extension, or just remove the compileCommands option from the c_cpp_properties.json we generate. The second option is simpler, since the first would require changes in the CLI (to generate a separate compile_commands for VSCode) and Kernel (to update the gitignore) as well.

:bug: Don't add compileCommands to c_cpp_properties

---

src/one-click/install.ts

This option is for people who want to re-install the CLI using an alternate method but don't want to uninstall everything else.

:sparkles: Add option to uninstall CLI only

---

src/device.ts

Previously we used an enum to match device type numbers to device names, but this limited by the enum naming rules. This replaces the enum with a Typescript Record, which lets us map device type numbers to strings.

:sparkles: Improve v5 device names in Brain View

---

src/commands/runvision.ts
src/one-click/download.ts
src/one-click/install.ts

Previously installing and running Vision Utility was unsupported on MacOS. This was due to adm-zip not properly creating the symbolic links in the MacOS app needed for it to run, corrupting the application. This PR fixes that by directly using the `unzip` executable that comes with MacOS to unzip the application and exec-ing the binary executable contained in the MacOS application directly, since spawning it from BaseCommand doesn't work properly.

:bug: Make Vision Utility work on MacOS

---

media/projectPros.js
src/views/editor.ts

Icon originally accessed github repository for image files and thus did not work offline. Fixed to access local files instead.

🐛 Fixed bug where icons do not appear when offline

---

package-lock.json
package.json
src/device.ts
src/views/brain-view.ts

Makes the node-usb package an optional dependency, since it cannot be installed on Windows ARM. This allows the extension to run on Windows ARM computers. Making node-usb an optional dependency should still install the package on other operating systems.
Reference: #230

:bug: Make usb an optional dependency for Windows ARM

---

package-lock.json
package.json
src/one-click/download.ts
src/one-click/install.ts

Before release, I found some bugs in weird edge cases:
1. lzma-native does not have a version build for Windows ARM, just like node-usb
2. Installing pros cli from pip causes semver to freak out because it reports version number as four numbers (ex. 3.5.4.0)
I am fixing these by:
1. Making lzma-native an optional dependency, just like I did for node-usb. This should be fine, since lzma-native is only used to extract the toolchain xz files on mac and linux, and the windows toolchain is a zip file.
2. Coercing the pros cli version number so semver is happy

:bug: fix some bugs in weird edge cases

---

src/one-click/install.ts
src/one-click/installed.ts

Some users had issues with the new version because they had installed the toolchain through other means. This was because there was a typo in the command to get the version of externally installed toolchains. This PR fixes that issue, and adds some additional logging for toolchain installation information for better debugging of these sorts of issues.

:bug: Fix getting version of externally installed toolchain

---

src/one-click/download.ts

Fix macos not installing toolchain

---

src/one-click/install.ts

So apparently the new CLI's behavior changed slightly, which causes the CLI verification after installing to fail. So instead of looking for machine output, we will now just check that `pros --version` returns correctly.

:bug: fix cli verification for new cli version
