- package-lock.json
- package.json
- src/commands/cli-parsing.ts
- src/commands/create-project.ts
- src/commands/index.ts
- src/commands/upgrade-project.ts
- src/commands/upload.ts
- src/extension.ts
- src/views/tree-view.ts
Using interactive UI with VSCode's very limited user input options was proving to be an issue, so I'm completely bypassing the middleware at the moment in favor of direct CLI calls. Not sure if that's the best approach really, but it seems to work for now....
Added three customized commands:
- Uploading
- Upgrading
- Creating a new project
All of the other user actions seem to work fine as terminal calls.
Closes #4
> Basic Commands

- media/projectPros.js
- media/reset.css
- media/vscode.css
- package.json
- src/editor.ts
- src/extension.ts
Allows the user to more easily set the project's name and upload slot when modifying project.pros.
Closes #4.
> Custom Editor for project.pros

- src/commands/build.ts
- src/commands/buildUpload.ts
- src/commands/clean.ts
- src/commands/index.ts
- src/extension.ts
Runs the rest of the commands through the extension instead of the terminal
> Add Commands 

- package.json
> Add basic settings

- package-lock.json
- package.json
- src/extension.ts
- src/ga.ts
Closes #13.
Posts analytics info to the VSCode Google Analytics property in the SIGBots account (UA-84548828-7).
> Add Google Analytics

- src/commands/build.ts
- src/commands/upload.ts
- src/extension.ts
> use build + upload cmds for quick action

- src/views/editor.ts
> Parse slot to integer

- CHANGELOG.md
- README.md
- package.json
- src/views/editor.ts
> Release 0.1.1

- src/commands/build.ts
- src/commands/buildUpload.ts
- src/commands/clean.ts
- src/commands/upgrade-project.ts
- src/commands/upload.ts
There have been reports of issues with paths not being found.
> Change references to fsPath

- CHANGELOG.md
- README.md
- azure-pipelines.yml
- package.json
- src/commands/build.ts
- src/commands/buildUpload.ts
- src/commands/clean.ts
- src/commands/upgrade-project.ts
- src/commands/upload.ts
Fix broken path bug by changing usage to fsPath.
> 🔖 Release 0.1.2

- package-lock.json
- package.json
- src/commands/build.ts
- src/commands/buildUpload.ts
- src/commands/clean.ts
- src/commands/create-project.ts
- src/commands/upgrade-project.ts
- src/commands/upload.ts
- src/extension.ts
- src/install.ts
- src/one-click/download.ts
- src/one-click/install.ts
- src/one-click/installed.ts
- src/views/tree-view.ts
- src/views/welcome-view.ts
This allows users to install the PROS CLI and Toolchain all inside of VSCode, this should simply the PROS install process significantly. Closes #12
> ✨One-Click

- .vscode/settings.json
- src/commands/cli-parsing.ts
Fixes the current issue where the PROS output still has ANSI escape keys in it.
> Remove ansi escape keys from make output

- src/extension.ts
- src/one-click/download.ts
- src/one-click/install.ts
Figured I'd open a PR rather than pushing directly to @BennyBot 's branch.
I forgot that I had the Prettier JS extension enabled, so a whole lot of these changes are just formatting changes 😬 I've marked the actually relevant changes.
Basically this got the file permissions stuff working and set the PATH properly in the terminal in my testing.
> A few fixes from my MacOS One-Click testing

- src/one-click/install.ts
Found in my testing of #53 .
On my Intel MacOS machine the pros executable could not be found in the PROS terminal because the PATH variable woudn't be parsed with spaces in the folder paths. Escaping those spaces allows me to run `pros` from the PROS terminal _and_ compile with `arm-none-eabi-g++`.
> One-click patch: Escape whitespace in paths

- src/commands/buildUpload.ts
Saw a couple of issues about build and upload working separately but not together. This _should_ resolve it.
#62
> 🐛Add Max Buffer for Build and Upload

- CHANGELOG.md
- package.json
- src/one-click/install.ts
> 🔖Release 0.4.2

- package.json
> ✨Add keywords

- .github/ISSUE_TEMPLATE/bug-report-template.md
- .github/ISSUE_TEMPLATE/feature-request-template.md
add some templates for bug reports and feature requests
> Update issue templates

- package.json
- src/extension.ts
- src/logger.ts
- src/one-click/download.ts
- src/one-click/install.ts
- src/one-click/installed.ts
- src/views/tree-view.ts
**This has not been tested much. Needs a lot of testing on all platforms.**
- Remove the `Update CLI` button because it did nothing.
- Use verification logic for the `Install PROS` button to choose between installing the CLI, Toolchain, or both
- Add a logger that will log actions taken by the one-click installer. Logs are timestamped. **Probably needs some more improvement before merge.**
- Maybe fix path issues on mac??? *needs more testing*
- Clear download directory after installation to take up less disk space.
Closes:
#72 #84
> 🐛✨One-Click improvements/log file

- package.json
I added key binds for the following commands:
Show Pros Terminal: ctrl/cmd +shift+i
Build Pros Project: ctrl/cmd +shift+b
Upload Pros Project: ctrl/cmd +shift+u
Build and Upload Pros Project: ctrl/cmd +shift+m
Open Brain Terminal: ctrl/cmd +shift+t
Closes #100
> ✨Add Keybinds for common commands

- src/commands/base-command.ts
- implements the run_command function in Base_Command
- add a basic constructor for testing
> Implement run_command()

- .vscode/settings.json
- src/commands/base-command.ts
- src/commands/build.ts
- src/extension.ts
Still have my testing code in Build.ts.
> Extension/fix sidebar buttons/create output parser

- src/commands/base-command.ts
- src/logger.ts
- Kill child process when cancel button is pressed
- Handle errors thrown by parse_output
> run_command improvements

- src/one-click/download.ts
- src/one-click/install.ts
- src/one-click/installed.ts
- src/one-click/path.ts
Does what the title says. Probably want to figure out a way to fetch the latest vexcom version so the download links aren't hard-coded in the future.
> ✨Add Vexcom to OneClick

- package.json
- src/extension.ts
Does what the title says. Needs extensive testing to make sure configurations work across all platforms (it is probably missing a couple of fields or some fields are incorrect in specific instances). My VSCode environment is acting up so I can't test until I get that fixed.
Closes #83
> ✨Generate Properties File for Microsoft C/C++ Extension

- package.json
- src/commands/command_tools.ts
- src/commands/index.ts
- src/commands/set-robot-name.ts
- src/commands/set-team-number.ts
- src/extension.ts
- src/views/tree-view.ts
Adds Set Team Name and Set Robot Name commands and add them to tree view as well. Should we add some sort of CLI version check to these? Does the Tree View need to be reorganized? Does PROS_VSCODE_FLAGS need to be added to every command?
> ✨Add Set Team Name and Set Robot Name

- src/commands/base-command.ts
- src/commands/buildUpload.ts
- src/commands/upload-command.ts
- src/commands/upload.ts
- Create UploadCommand, which parses machine output to make a progress bar for uploading.
- Change upload to use UploadCommand, and buildUpload to run build and upload.
- Fix some regex stuff
> ✨Add progress bar for uploading

- .vscode/settings.json
- package.json
- src/commands/capture.ts
- src/commands/command_tools.ts
- src/commands/create-project.ts
- src/commands/upgrade-project.ts
- src/extension.ts
Closes #140 .
I had to make some changes to command_tools.ts and redid the entire command registration portion of extension.ts. This needs some thorough testing before it gets approved and merged.
> 🐛 Prevent Commands from Running Multiple Times

- .github/workflows/pull_request.yml
This should fix the errors currently going on in CI
> Bump the Prettier GH Action version

- src/commands/run.ts
Read `project.pros` file to find the slot for the program, which is then used for the Run command.
Closes #134
> 🐛 Detect Slot for Run Command

- package-lock.json
- package.json
- src/device.ts
- tsconfig.json
Resolves issue #156 
- Add `--no-analytics` argument to `pros lsusb` calls
- Use `usb` library to detect when devices connect/disconnect
> 🐛 Improve Device Connect/Disconnect Detection

- package-lock.json
- package.json
- src/commands/build.ts
- src/commands/clean.ts
- src/commands/create-project.ts
- src/commands/fw-update.ts
- src/commands/run.ts
- src/commands/runmedic.ts
- src/commands/runvision.ts
- src/commands/set-robot-name.ts
- src/commands/set-team-number.ts
- src/commands/stop.ts
- src/commands/upgrade-project.ts
- src/commands/upload-command.ts
Also suppressed completion messages for some commands i.e. "run" because it seems obnoxious to have that many popups when you can clearly tell if it's running or not. 
I ran npm install usb to resolve an error I had preventing me from running the extension, this caused a ton of changes to one of the json things, but it works on my computer with those changes so maybe not an issue (?).
> ✨ Descriptive Command Completion Messages

- package-lock.json
- package.json
Microsoft split up the vscode package across @types/vscode and vscode-test. Set the minimum version for @types/vscode to the most recent, which resolved some of the mysterious error messages.
> ⬆️ Update vscode package

- src/one-click/install.ts
- src/one-click/installed.ts
Does what the title says. Closes #174. Not a complete overhaul of every message since #176 will be coming in the future anyways.
> ♿ Improve One-Click Messages

- src/extension.ts
The last PR had some problems that weren't caught in the merge conflicts (multiple definition issues). This fixes them.
> 🐛 Fix extension compilation problems

- azure-pipelines.yml
- package-lock.json
- package.json
Since we updated @types/vscode, we also need to update the vscode engine version to match it.
> :bug: Update engine.vscode version

- src/extension.ts
For some reason this fixes the command to open the pros logs.
> :bug: Fix Open Logs Command

- package.json
> 🐛 Only display PROS buttons if we are in a PROS Project

- .vscode/settings.json
- package-lock.json
- package.json
- src/one-click/download.ts
unzipper is broken now for some reason so this PR just switches to adm-zip to extract zip files after downloading.
> 🐛 switch from unzipper to adm-zip

- package-lock.json
- src/extension.ts
- src/views/welcome-view.ts
Does what the title says
close #223
> 🐛 Use tag versions to select CLI version on welcome screen

- package-lock.json
- package.json
- src/commands/index.ts
- src/commands/reset-conductor.ts
- src/extension.ts
- src/views/tree-view.ts
- src/views/welcome-view.ts
Hotfix to add reset conductor button
> 🔖 Release 0.7.3
